### ISSUE TITLE
Update to newest waveshare_epd

### ISSUE THREAD

**Issue by theGOTOguy** [yskoht/waveshare-epaper#1]
Thank you for creating this `pip` module.  This is a vastly improved experience from the official Waveshare Python libraries.

Since your last release, [support for more Waveshare e-paper products has been added](https://github.com/waveshare/e-Paper/tree/master/RaspberryPi_JetsonNano/python/lib/waveshare_epd).  Can you cut a new release that adds the products from head?

If time is an issue, I can create a PR if you will merge and release an updated version.

**Comment by yskoht** [comment]
@theGOTOguy 

Thank you!

I updated the `epapre/e-Paper` submodule to `60762ac5a3787ca7c3080d0e1f256a32ec3147e6` from `1ac5cbad562ed58c678ba0d6f3f833612ec53320`.

This change was released in `waveshare-epaper@1.2.0`.
